In [45]:
import os
import sys
import numpy as np
import warnings
# Ignore warnings
warnings.filterwarnings('ignore')
from PIL import Image

import cv2

In [17]:
#change directory to the folder where the data is stored
dogs_dir = 'C:/Users/Lenovo/Desktop/data_class/dog_photos1/'

In [18]:
cars_dir =  'C:/Users/Lenovo/Desktop/data_class/car_photos1/'

In [19]:
#list off all objects in the folder
dogs = os.listdir(dogs_dir)

In [20]:
cars = os.listdir(cars_dir)

In [21]:
#shape of the all image in the folder
dogs_shape = []

#loop through all objects in the folder
# for flower in flowers:
#get the path of the image
dog_path = dogs_dir + dogs[0]

dog_path

'C:/Users/Lenovo/Desktop/data_class/dog_photos1/01438529bd59fb9b5fd32f65b598fd17.png'

In [53]:
#for loop for all images
for dog in dogs:
    #get the path of the image
    dog_path = dogs_dir + dog
    #read the image


    dog_gray  = cv2.imread(dog_path, cv2.IMREAD_GRAYSCALE)
    resized = cv2.resize(dog_gray, (75,75), interpolation = cv2.INTER_AREA)


error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4052: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'


In [48]:
#for loop for all images
for dog in dogs:
    #get the path of the image
    dog_path = dogs_dir + dog
    #read the image
    dog_gray  = cv2.imread(dog_path, cv2.IMREAD_GRAYSCALE)
    
    print(dog_gray)

[[135 150 154 ... 171 207 189]
 [126 123 128 ... 162 192 181]
 [119 120 125 ... 100 104 108]
 ...
 [ 51  52  57 ...  53  56  52]
 [ 46  51  53 ...  57  55  54]
 [ 46  51  49 ...  60  60  64]]
[[165 205 230 ... 155 104 104]
 [168 201 223 ... 123  99  99]
 [174 194 210 ...  92  98  98]
 ...
 [ 97 104 131 ... 146 127 127]
 [112 120 123 ... 145 126 126]
 [112 120 123 ... 138 136 136]]
[[154 147 137 ...  82  26  12]
 [151 144 135 ...  35  28  14]
 [149 142 134 ...  36  31  17]
 ...
 [194 206 159 ... 167 180 180]
 [197 162 109 ... 168 188 161]
 [180 147  99 ... 159 153 126]]
[[117 117 117 ... 114 113 113]
 [117 117 117 ... 114 113 113]
 [117 117 117 ... 115 114 114]
 ...
 [219 218 215 ... 157 160 160]
 [218 215 212 ... 157 156 156]
 [218 215 212 ... 157 156 156]]
[[ 43  45  46 ...  37  42  42]
 [ 44  46  48 ...  42  46  46]
 [ 45  47  48 ...  45  45  45]
 ...
 [141 139 159 ... 170 154 154]
 [147 157 160 ... 164 153 153]
 [138 147 151 ... 155 143 143]]
[[245 248 234 ... 182 193 193]
 [245 250

In [23]:
for car in cars:
    #get the path of the image
    car_path = cars_dir + car
    #read the image
    car_img = Image.open(car_path)
    #set size of all images 256x256 in for loop
    car_img = car_img.resize((50,50))
    #gray scale
    car_img = car_img.convert('L')
    #save the image
    car_img.save(cars_dir + car)

UnidentifiedImageError: cannot identify image file 'C:/Users/Lenovo/Desktop/data_class/car_photos1/22_LV_Trofeo_PS_T1_HomePage_1920x1080.jpg'